### ISSUE TITLE
Swift Syntax Highlighting

### ISSUE THREAD

**Issue by bitigchi** [arzg/vim-colors-xcode#3]
Vim currently ships with Swift syntax highlighting, written by Swift developers. It would be really cool to have the exact Xcode syntax highlighting with this great color scheme.

https://github.com/vim/vim/blob/master/runtime/syntax/swift.vim
https://github.com/vim/vim/blob/master/runtime/syntax/swiftgyb.vim
https://github.com/vim/vim/blob/master/runtime/syntax/sil.vim

**Comment by arzg** [comment]
> It would be really cool to have the exact Xcode syntax highlighting

I would agree that that would be very cool, but I believe that it is almost impossible to achieve this. mainly because Xcode separates ‘local’ and ‘library’ identifiers through analysis that cannot be achieved through Vim’s syntax regexes alone. The reason for this is that if a type, function or identifier is preceded by a module path, you can assume in most cases that it is from a library. But the moment you start `import`ing things the syntactical distinction between library and local items is destroyed.

If you were happy to give up this distinction then I think it might be possible to get pretty close.

I tried to use the built in one with both Vim 8.2 and NeoVim 0.5, but it didn’t work, so I tried a few from GitHub:

- toyamarinyon/vim-swift, but it highlights function calls as Identifier
- keith/swift.vim, but it doesn’t highlight function calls at all
- lilyball/vim-swift, but the indentation is broken and non-default function calls aren’t highlighted (e.g. `print()` is highlighted but `frobnicate()` isn’t)
- bumaociyuan/vim-swift (this is apparently a copy of Apple’s official plugin, since I couldn’t get Apple’s one), but function calls aren’t highlighted and indentation is broken

Due to these issues it might be worth attempting to write our own. I’ve never written a Vim syntax plugin before, so this could be a learning experience :)

> this great color scheme

Aww, thanks :)

**Comment by bitigchi** [comment]
Thanks for your detailed reply, I really appreciate it. I have also observed the differences you mentioned before too. And yes, whatever closest would be the best.

> I tried to use the built in one with both Vim 8.2 and NeoVim 0.5, but it didn’t work, so I tried a few from GitHub:

Did you try with the latest releases? I am able to get Swift syntax highlighting, actually I was the one who tested and helped incorporate it into the source code. Since this comes directly from Swift developers, I don't think any other variant would come close (haven't tested though), it looks pretty thorough to me.

**Comment by arzg** [comment]
> Did you try with the latest releases?

I just updated to Vim 8.2 with patches 1–150 and deleted my config. It definitely works now (thanks for your work on this!), but has exactly the same behaviour of bumaociyuan/vim-swift. Would you be ok with me starting development of a new Swift language plugin from scratch that attempts to mimic the details of Xcode’s highlighting, or would you prefer for me to simply take one of the existing plugins and try to make it match as much as possible?

**Comment by bitigchi** [comment]
> > Did you try with the latest releases?
> 
> I just updated to Vim 8.2 with patches 1–150 and deleted my config. It definitely works now (thanks for your work on this!), but has exactly the same behaviour of bumaociyuan/vim-swift. Would you be ok with me starting development of a new Swift language plugin from scratch that attempts to mimic the details of Xcode’s highlighting, or would you prefer for me to simply take one of the existing plugins and try to make it match as much as possible?

That would be really nice of you to try to fix this, I would love it. I'd like to propose something better; as far as I can see, Swift developers always welcome outside patches. I'm sure they would welcome your fixes, so that everyone can have it out of the box. If they don't include your fixes, well, that's on them :). But of course I do respect if you want to keep it as your separate thing, mine was just an idea.

Thank you!

**Comment by arzg** [comment]
> I'm sure they would welcome your fixes, so that everyone can have it out of the box.

I’ll take a look at Apple’s Swift Vim plugin and see if what I’ve hacked together so far would be a good fit for the codebase. The main implementation difference between the Apple one and mine is that I decided to define a separate highlight group for every item (to make it easier for people to customise), whereas Apple’s one just puts all related items under a single one.

> But of course I do respect if you want to keep it as your separate thing

Hmm, I kind of like the idea of starting afresh (I understand that this is a big problem developers have), but I do get that the possibility of this added highlighting helping people (I’m not sure how much it actually helps though 😄) is much greater if it is shipped by default.

---

So far my implementation includes a _lot_ of keywords (I’ve never actually written Swift so I was surprised by how many there are, being familiar with Rust), a list of all the standard library types (Vim was very handy here) and support for user-defined types.

Next I’m going to add support for functions. As I would like to replicate Xcode’s local/library highlighting distinction, would you have any idea how to differentiate local/library functions by syntax alone? If it’s not possible, would it be more accurate to assume that all function are from libraries or are local to the project? Does the same go for methods?

Thank you so much for your help with this issue :)

---

By the way, I am interested in what your use case for this project is? Is it that you like the way Xcode looks, but prefer Vim’s editing model? Or is it something else entirely? Personally, after having played around with it for a bit, I find Xcode’s autocomplete to be a no-brainer, and I cannot imagine giving that up, given the choice.

**Comment by bitigchi** [comment]
> Next I’m going to add support for functions. As I would like to replicate Xcode’s local/library highlighting distinction, would you have any idea how to differentiate local/library functions by syntax alone? If it’s not possible, would it be more accurate to assume that all function are from libraries or are local to the project? Does the same go for methods?

I don't see a way to do it unless list of Swift libraries are provided somehow. But it might be possible to tap into that on a macOS system (albeit a challenge). I'd suggest looking at the [SourceKit](https://github.com/apple/swift/tree/master/tools/SourceKit) code for implementation. Maybe read from the same libraries that Xcode reads from (though I have no idea how to do that)?

For other Unix clones, it would not harm to provide one color for both system libraries and user-defined functions/methods. Blue for definitions, Purple for calls (going the system route here).

> By the way, I am interested in what your use case for this project is? Is it that you like the way Xcode looks, but prefer Vim’s editing model? Or is it something else entirely? Personally, after having played around with it for a bit, I find Xcode’s autocomplete to be a no-brainer, and I cannot imagine giving that up, given the choice.

I was playing with command line Swift, and the idea evolved from there :). I think Swift has great potential as a scripting language. Although Linux support is currently far from ideal at the moment, I'd like to think it will be common in the future as well. Thus, providing decent support for Vim, and laying the groundwork for a nice working environment, it would still help adoption.

**Comment by arzg** [comment]
> Maybe read from the same libraries that Xcode reads from (though I have no idea how to do that)?

Hmm, that sounds very difficult, especially considering that Vim uses regex for syntax.

>  Purple for calls (going the system route here).

Ok, going by that I assume that you would prefer to assume that function calls are from libraries?

**Comment by arzg** [comment]
I’ve added a lot to [vim-swift](https://github.com/arzg/vim-swift) – could you please take a look and let me know what you think of it?

**Comment by bitigchi** [comment]
Screenshot looks great -- I'll try and give feedback as soon as I can!

**Comment by arzg** [comment]
Thanks for the compliment!

**Comment by bitigchi** [comment]
I'm not getting the exact same colour variant, which color scheme variant should I use?

**Comment by arzg** [comment]
The screenshot was with no custom settings and the dark variant `xcodedark`. I added some extra highlight links for Swift in the last commit – maybe you need to update?

**Comment by bitigchi** [comment]
No, I just pulled the file before posting the message. In my case:

Variables are green instead of cyan, white when called,
Import statements are highlighted orange, imported libraries are cyan
Types are cyan, instead of purple
User methods are purple,
Struct definitions are white, instead of cyan.

I'm using the dark variant without any setting as well.

**Comment by arzg** [comment]
Can you show the output of `:verbose hi swiftTypeDef` and `:verbose hi swiftIdentDef` and `:verbose hi swiftUserFunc`?

**Comment by bitigchi** [comment]
```vimL
:verbose hi swiftTypeDef
swiftTypeDef   xxx links to Typedef
        En son şuradan ayarlandı: ~/.vim/syntax/swift.vim satır 307
```

```vimL
:verbose hi swiftIdentDef
swiftIdentDef  xxx links to Identifier
        En son şuradan ayarlandı: ~/.vim/syntax/swift.vim satır 295
```

```vimL
:verbose hi swiftIdentDef
swiftIdentDef  xxx links to Identifier
        En son şuradan ayarlandı: ~/.vim/syntax/swift.vim satır 295
```

**Comment by arzg** [comment]
Looks like the colourscheme’s custom links aren’t applying. Could you please run this:

```bash
$ mkdir -p ~/.vim/pack/bundle/vim-swift/syntax
$ mv ~/.vim/syntax/swift.vim ~/.vim/pac/bundle/vim-swift/syntax/
```

**Comment by bitigchi** [comment]
This is falling back to vim-default syntax highlighting (doesn't read it).

**Comment by arzg** [comment]
I pushed a fix – should be working now.

**Comment by bitigchi** [comment]
Looks much better now, thanks!

Only a couple of issues remain:
* `import` statements are still highlighted orange, imported library highlighted cyan
* `struct` declarations are not highlighted cyan, `class` declarations seem fine
* Variables/Constants that are objects of another class/struct are not highlighted when called. I am not sure how to achieve this though

Not that these issues particularly bother me, just putting on record. Thank you for your great work on this, particularly brilliant! For the next step (if you are willing of course) .sil and .swiftgyb file types would be nice to have as they are the part of the package). For my use case this is more than enough.

**Comment by arzg** [comment]
> Thank you for your great work on this

Thanks for the compliments and for helping me find bugs :)

> import statements are still highlighted orange

Just fixed this now.

> `struct` declarations are not highlighted cyan, `class` declarations seem fine

I can’t seem to reproduce this. It’s especially strange, since the code for highlighting [structs](https://github.com/arzg/vim-swift/blob/4a5f588ce57beef7a0b5712360365895b82df9d2/syntax/swift.vim#L118), [classes](https://github.com/arzg/vim-swift/blob/4a5f588ce57beef7a0b5712360365895b82df9d2/syntax/swift.vim#L97) and [enums](https://github.com/arzg/vim-swift/blob/4a5f588ce57beef7a0b5712360365895b82df9d2/syntax/swift.vim#L102) is identical (apart from the keyword).

> Variables/Constants that are objects of another class/struct are not highlighted when called

Do you with this mean [properties](https://docs.swift.org/swift-book/LanguageGuide/Properties.html)? Because I’ve already added [highlighting for properties](https://github.com/arzg/vim-swift/blob/4a5f588ce57beef7a0b5712360365895b82df9d2/syntax/swift.vim#L190) …

For example, `.west` in the example screenshot is highlighted as a property. (I know it isn’t one, but it has the same syntax and therefore gets the same highlighting.)

> .sil and .swiftgyb

Is the file extension `.swift.gyb`, just `.gyb`, or is it `.swiftgyb`. I found [an article about GYB](https://nshipster.com/swift-gyb/) and it seems to use `.swift.gyb`

**Comment by bitigchi** [comment]
Most interestingly, when I created a new file, `struct` highlighting worked, but for an existing file, it did not. Can you please check with [this file](https://github.com/bitigchi/mccCore/blob/master/Sources/mccCore/mccCore.swift)?

For the properties' case, Xcode would highlight `string` as well, that was what I meant. But that's trivial.

And yes, `swift.gyb`. Sorry for the omission! :)

**Comment by arzg** [comment]
> Can you please check with this file

It looks like the type in that file, `mccCore`, starts with a lowercase letter. I defined type definitions so that they must always begin with an uppercase letter, since my research told me that types in Swift tend to be capitalised. Is this correct?

> Xcode would highlight string as well

Hmm, would this just be `syntax match swiftUserIdent '\v<[a-z][A-Za-z0-9]>'`?

> And yes, swift.gyb

Does this have the same syntax as Swift? So can I just set its filetype to `swift`?

> Sorry for the omission! :)

No problem :)

**Comment by bitigchi** [comment]
> It looks like the type in that file, `mccCore`, starts with a lowercase letter. I defined type definitions so that they must always begin with an uppercase letter, since my research told me that types in Swift are capitalised. Is this correct?

Oh shoot, this was my exception in that case... So yes, NOTABUG. Xcode probably uses a different kind of syntax checking to highlight those no matter what.

> Hmm, would this just be `syntax match swiftUserIdent '\v<[a-z][A-Za-z0-9]>'`?

Looks like so... But I'm not the best expert out there...
 
> Does this have the same syntax as Swift? So can I just set its filetype to `swift`?

I really haven't dealt with that type of file, since it's use case is kind of niche. :) But there should be examples on the net to give you an idea.

**Comment by arzg** [comment]
> Looks like so

It’s in now under `g:swiftHighlightIdents`.

> I really haven't dealt with that type of file

I’ve left it out for now – if someone else asks about it I’ll look into it further, if that doesn’t bother you :)

**Comment by bitigchi** [comment]
Thank you for all your labour! It’s kind of rare to see a feature request get implemented so Swift!

Also curious, is this implementation colour theme agnostic? Say, if I try this with a different colour scheme, the highlighting pattern would be the same?

**Comment by arzg** [comment]
> Thank you for all your labour!

No problem, thank you for bringing up this discussion :)

> is this implementation colour theme agnostic?

By default vim-swift will link the user-specific and library-specific highlight groups to the same highlight group, with vim-colors-xcode overriding these and providing custom highlighting.

> if I try this with a different colour scheme, the highlighting pattern would be the same?

The same things would be highlighted, but things like identifier definitions and actual identifiers will get the same highlighting. The same goes for function definitions and function calls, user types and library types, etc.

**Comment by bitigchi** [comment]
Thank you for the info!

**Comment by arzg** [comment]
Can this issue be closed?

**Comment by arzg** [comment]
Thanks for all your help :)

**Comment by bitigchi** [comment]
> Thanks for all your help :)

No problem! With pleasure.

**Comment by bitigchi** [comment]
Just another thing, statements starting with @ are not highlighted properly (@IBAction, @objc etc.). They should be purple as well, but they are cyan currently.

**Comment by arzg** [comment]
> statements starting with @ are not highlighted properly

Ah, ok. Is there a name for that kind of statement? And what characters are permitted in them?

**Comment by arzg** [comment]
I think it would be better to have this discussion in the vim-swift repo. Is that ok with you?

**Comment by bitigchi** [comment]
Sure!
